version: 0.2

env:
  variables:
    TERRAFORM_WORKDIR: "terraform/ec2"
    S3_BUCKET: "go-s3-bucket-test"

phases:
  install:
    commands:
      # - yum update -y --allowerasing
      - yum install -y unzip curl --allowerasing
      - curl -fLO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - mkdir -p /tmp/terraform-bin
      - unzip -o terraform_1.6.6_linux_amd64.zip -d /tmp/terraform-bin
      - mv /tmp/terraform-bin/terraform /usr/local/bin/
      - terraform version

  build:
    commands:
      - |
        if [ "$ACTION" = "destroy" ]; then
          cd $TERRAFORM_WORKDIR
          terraform init -reconfigure
          terraform destroy -auto-approve
        else
          cd $TERRAFORM_WORKDIR
          terraform init -reconfigure
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          terraform output -json > ../../ansible/outputs.json
          terraform output -json > terraform-outputs.json || echo "{}" > terraform-outputs.json
          aws s3 cp terraform-outputs.json s3://$S3_BUCKET/terraform-outputs.json --region $AWS_REGION
          aws s3 cp ../../ansible/outputs.json s3://$S3_BUCKET/ansible-outputs.json --region $AWS_REGION
        fi

artifacts:
  files:
    - terraform-outputs.json
    - ansible/outputs.json