- name: OS config (RHEL only)
  hosts: dbservers
  become: yes
  gather_facts: yes

  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      when: ansible_os_family == "RedHat"

    - name: Disable firewalld
      ansible.builtin.systemd:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_os_family == "RedHat"

    - name: Ensure SSM agent running
      ansible.builtin.service:
        name: amazon-ssm-agent
        state: started
        enabled: yes