# ==============================
# SSM接続設定
# ==============================

ansible_aws_ssm_region: ap-south-1
ansible_aws_ssm_s3_bucket: go-s3-bucket-test
ansible_python_interpreter: /usr/bin/python3
ansible_aws_ssm_timeout: 60
