---
- name: Common services for all servers
  hosts: dbservers
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Install Python pip for RHEL 9
      yum:
        name: python3-pip
        state: present
    - name: Install boto3 library
      pip:
        name: boto3
        executable: /usr/bin/pip3
  tasks:
    - name: Gather facts
      setup:
  roles:
    - common

# 個別サービスは roles/db などに分離して追加できます
# 例:
# - name: DB専用サービス
#   hosts: dbservers
#   become: yes
#   roles:
#     - db